### PR TITLE
[Feature] add image pull secrets

### PR DESCRIPTION
**Pull request by barloc**
Add image pull secrets for private repos. 
Secrets must be exist in the k8s cluster.

### CODE REVIEW

**Review by LamaAni — CHANGES_REQUESTED** [review]
Hi can you uncouple this PR from the mount_files_from_secret? 

Otherwise approved!

**Comment by LamaAni** [comment]
Hi, sorry for the late reply. Was traveling. Any progress on this?

**Comment by barloc** [comment]
Waiting for #88

**Comment by barloc** [comment]
oops, i'll fix it soon

**Comment by LamaAni** [comment]
Hi, any updates on this?

**Pull request closed without merging**
