### PR TITLE
Readme k8s acl (next try)

### PR DESCRIPTION
**Pull request by barloc**
Sorry, I don't understand how to merge previous PR.

### CODE REVIEW

**Comment by LamaAni** [comment]
Sure thing. This still has issues with the current master branch (you need to sync the branches with your fork). I'll updated it. Tnx for the PR!

**Comment by barloc** [comment]
Madness. I tried to create new branch from current master with changes, but conflict is there too.

**Comment by LamaAni** [comment]
I'll just add it

**Comment by LamaAni** [comment]
Fixed in https://github.com/LamaAni/KubernetesJobOperator/pull/78 (Thank you!)

**Pull request closed without merging**
